/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AgentSessions {
  agent_identifier: string;
  connection_method: string;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  delivery_state: string;
  ended_at: string | null;
  external_session_id: string | null;
  id: string | null;
  last_heartbeat_at: string | null;
  metadata_json: Generated<string>;
  model_identifier: string | null;
  objective_id: string;
  phase: string;
  project_id: string;
  revision: Generated<number>;
  session_key_hash: string;
  session_key_prefix: string;
  started_at: string;
  ticket_id: string;
  updated_at: string;
  workspace_id: string;
}

export interface Artifacts {
  content_json: string | null;
  content_text: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  delivery_id: string | null;
  external_url: string | null;
  id: string | null;
  label: string;
  objective_id: string | null;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  ticket_id: string;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface ChangedFiles {
  created_at: string;
  current_diff_state: string;
  deleted_at: string | null;
  file_path: string;
  first_observed_at: string;
  id: string | null;
  last_observed_at: string;
  last_observed_event_id: string | null;
  objective_id: string;
  observed_metadata_json: Generated<string>;
  project_id: string;
  resource_id: string | null;
  revision: Generated<number>;
  session_id: string | null;
  ticket_id: string;
  updated_at: string;
  vcs_status: string | null;
  workspace_id: string;
}

export interface ChangeRationales {
  changed_file_id: string | null;
  created_at: string;
  deleted_at: string | null;
  delivery_id: string | null;
  file_path: string;
  hunks_json: Generated<string>;
  id: string | null;
  impact: string;
  is_final: Generated<number>;
  label: string;
  objective_id: string;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  source_event_id: string | null;
  summary: string;
  ticket_id: string;
  updated_at: string;
  why: string;
  workspace_id: string;
}

export interface Deliveries {
  created_at: string;
  deleted_at: string | null;
  delivered_at: string;
  delivered_by_workspace_user_id: string | null;
  follow_up_notes: string | null;
  id: string | null;
  objective_id: string;
  payload_json: Generated<string>;
  project_id: string;
  revision: Generated<number>;
  session_id: string | null;
  summary: string;
  ticket_id: string;
  updated_at: string;
  verification_summary: string | null;
  workspace_id: string;
}

export interface Devices {
  created_at: string;
  deleted_at: string | null;
  fingerprint: string;
  id: string | null;
  label: string;
  last_seen_at: string | null;
  metadata_json: Generated<string>;
  platform: string | null;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface EntityChanges {
  actor_token_id: string | null;
  actor_workspace_user_id: string | null;
  changed_fields_json: Generated<string>;
  entity_id: string;
  entity_revision: number | null;
  entity_type: string;
  id: string;
  objective_id: string | null;
  occurred_at: string;
  operation: string;
  project_id: string | null;
  seq: Generated<number | null>;
  source: string;
  ticket_id: string | null;
  workspace_id: string;
}

export interface ExecutionRequests {
  attempt_count: Generated<number>;
  claim_expires_at: string | null;
  claimed_at: string | null;
  claimed_by_device_id: string | null;
  claimed_by_execution_target_id: string | null;
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string | null;
  id: string | null;
  idempotency_key: string | null;
  last_error: string | null;
  launch_completed_at: string | null;
  launch_flags_json: Generated<string>;
  launch_mode: string;
  launch_started_at: string | null;
  launched_session_id: string | null;
  metadata_json: Generated<string>;
  objective_id: string;
  project_id: string;
  requested_agent: string | null;
  requested_by_workspace_user_id: string | null;
  requested_model: string | null;
  requested_reasoning_effort: string | null;
  requested_source: string;
  resolved_resource_id: string | null;
  resolved_working_directory: string | null;
  revision: Generated<number>;
  status: string;
  target_kind: string;
  ticket_id: string;
  updated_at: string;
  workspace_id: string;
}

export interface ExecutionTargets {
  agent_flags_json: Generated<string>;
  connection_json: Generated<string>;
  created_at: string;
  deleted_at: string | null;
  device_id: string | null;
  id: string | null;
  label: string;
  owner_workspace_user_id: string | null;
  revision: Generated<number>;
  status: string;
  terminal_profile_json: Generated<string>;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface IdempotencyKeys {
  actor_workspace_user_id: string | null;
  created_at: string;
  expires_at: string;
  id: string | null;
  key: string;
  request_hash: string;
  response_json: string | null;
  scope: string;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface ObjectiveAttachments {
  checksum_sha256: string | null;
  content_type: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  filename: string;
  id: string | null;
  metadata_json: Generated<string>;
  objective_id: string;
  revision: Generated<number>;
  size_bytes: number | null;
  storage_backend: string;
  storage_key: string;
  ticket_id: string;
  updated_at: string;
  upload_status: string;
  workspace_id: string;
}

export interface Objectives {
  agent_flags_json: Generated<string>;
  approval_reason: string | null;
  assigned_agent: string | null;
  auto_advance: Generated<number>;
  auto_advanced_at: string | null;
  completed_at: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  execution_metadata_json: Generated<string>;
  id: string | null;
  instruction_text: string;
  launch_config_json: string | null;
  model: string | null;
  position: number;
  project_id: string;
  reasoning_effort: string | null;
  revision: Generated<number>;
  state: string;
  ticket_id: string;
  title: string | null;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectResources {
  created_at: string;
  deleted_at: string | null;
  execution_target_id: string | null;
  id: string | null;
  is_primary: Generated<number>;
  label: string | null;
  metadata_json: Generated<string>;
  path: string;
  project_id: string;
  revision: Generated<number>;
  status: string;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface Projects {
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  description: string | null;
  id: string | null;
  name: string;
  revision: Generated<number>;
  settings_json: Generated<string>;
  slug: string;
  status: string;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectStatuses {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  is_default: Generated<number>;
  is_terminal: Generated<number>;
  key: string;
  metadata_json: Generated<string>;
  name: string;
  position: number;
  project_id: string;
  revision: Generated<number>;
  type: string;
  updated_at: string;
  workspace_id: string;
}

export interface ProjectUserPreferences {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  preferences_json: Generated<string>;
  project_id: string;
  revision: Generated<number>;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface RoleAssignments {
  assigned_by_workspace_user_id: string | null;
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  resource_id: string;
  resource_type: string;
  revision: Generated<number>;
  role_key: string;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface SchemaMigrations {
  adapter: string;
  applied_at: string;
  checksum: string;
  component: string;
  contract_version: string;
  version: string;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface SharedContextEntries {
  created_at: string;
  created_by_session_id: string | null;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  id: string | null;
  key: string;
  objective_id: string | null;
  revision: Generated<number>;
  ticket_id: string;
  updated_at: string;
  value_json: string | null;
  value_kind: string;
  value_text: string | null;
  workspace_id: string;
}

export interface TicketEvents {
  actor_token_id: string | null;
  actor_workspace_user_id: string | null;
  created_at: string;
  external_url: string | null;
  id: string | null;
  idempotency_key: string | null;
  objective_id: string | null;
  payload_json: Generated<string>;
  phase: string | null;
  project_id: string;
  session_id: string | null;
  source: string;
  summary: string;
  ticket_id: string;
  type: string;
  workspace_id: string;
}

export interface Tickets {
  acceptance_criteria_text: string | null;
  assigned_workspace_user_id: string | null;
  available_tools_json: Generated<string>;
  board_position: Generated<number>;
  constraints_text: string | null;
  created_at: string;
  created_by_workspace_user_id: string | null;
  deleted_at: string | null;
  display_id: string;
  execution_target_intent_json: Generated<string>;
  id: string | null;
  metadata_json: Generated<string>;
  output_format_text: string | null;
  priority: string | null;
  project_id: string;
  revision: Generated<number>;
  sequence_number: number;
  status_id: string;
  status_type: string;
  title: string;
  updated_at: string;
  workspace_id: string;
}

export interface TicketSequences {
  counter_name: string;
  id: string | null;
  next_value: number;
  scope_id: string;
  scope_type: string;
  updated_at: string;
  workspace_id: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: Generated<number>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: string;
}

export interface Users {
  auth_provider: string | null;
  created_at: string;
  deleted_at: string | null;
  display_name: string;
  email: string | null;
  external_subject: string | null;
  handle: string | null;
  id: string | null;
  kind: string;
  metadata_json: Generated<string>;
  revision: Generated<number>;
  status: string;
  updated_at: string;
}

export interface UserTokens {
  created_at: string;
  deleted_at: string | null;
  expires_at: string | null;
  hash_algorithm: string;
  id: string | null;
  label: string;
  last_used_at: string | null;
  last_used_context_json: Generated<string>;
  metadata_json: Generated<string>;
  predecessor_token_id: string | null;
  revision: Generated<number>;
  revoked_at: string | null;
  revoked_by_workspace_user_id: string | null;
  status: string;
  token_hash: string;
  token_prefix: string;
  updated_at: string;
  user_id: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface UserTokenScopes {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  permission: string;
  resource_id: string | null;
  resource_type: string | null;
  revision: Generated<number>;
  token_id: string;
  updated_at: string;
  workspace_id: string;
}

export interface Verification {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface Workspaces {
  created_at: string;
  deleted_at: string | null;
  id: string | null;
  kind: string;
  name: string;
  revision: Generated<number>;
  settings_json: Generated<string>;
  slug: string;
  updated_at: string;
}

export interface WorkspaceUserExecutionTargets {
  access_status: string;
  agent_flags_json: Generated<string>;
  created_at: string;
  default_username: string | null;
  deleted_at: string | null;
  execution_target_id: string;
  id: string | null;
  last_connected_at: string | null;
  revision: Generated<number>;
  terminal_profile_json: Generated<string>;
  updated_at: string;
  workspace_id: string;
  workspace_user_id: string;
}

export interface WorkspaceUsers {
  created_at: string;
  deleted_at: string | null;
  display_name: string | null;
  id: string | null;
  member_key: string | null;
  metadata_json: Generated<string>;
  revision: Generated<number>;
  status: string;
  updated_at: string;
  user_id: string;
  workspace_id: string;
}

export interface DB {
  account: Account;
  agent_sessions: AgentSessions;
  artifacts: Artifacts;
  change_rationales: ChangeRationales;
  changed_files: ChangedFiles;
  deliveries: Deliveries;
  devices: Devices;
  entity_changes: EntityChanges;
  execution_requests: ExecutionRequests;
  execution_targets: ExecutionTargets;
  idempotency_keys: IdempotencyKeys;
  objective_attachments: ObjectiveAttachments;
  objectives: Objectives;
  project_resources: ProjectResources;
  project_statuses: ProjectStatuses;
  project_user_preferences: ProjectUserPreferences;
  projects: Projects;
  role_assignments: RoleAssignments;
  schema_migrations: SchemaMigrations;
  session: Session;
  shared_context_entries: SharedContextEntries;
  ticket_events: TicketEvents;
  ticket_sequences: TicketSequences;
  tickets: Tickets;
  user: User;
  user_token_scopes: UserTokenScopes;
  user_tokens: UserTokens;
  users: Users;
  verification: Verification;
  workspace_user_execution_targets: WorkspaceUserExecutionTargets;
  workspace_users: WorkspaceUsers;
  workspaces: Workspaces;
}
