/**
 * Database types for Overlord.
 *
 * `db.ts` is auto-generated by kysely-codegen — do not edit it directly.
 * Regenerate it with `yarn generate` after any schema migration.
 *
 * To define custom types that build on the generated schema, add them here
 * or in additional files in this directory, importing from `./db.js`.
 *
 * Example:
 *
 *   import type { Selectable } from 'kysely';
 *   import type { Tickets } from './db.js';
 *
 *   export type TicketRow = Selectable<Tickets>;
 *   export type ActiveTicket = TicketRow & { deleted_at: null };
 */

export type { Generated } from './db.js';
export type { DB } from './db.js';
export type {
  Account,
  AgentSessions,
  Artifacts,
  ChangedFiles,
  ChangeRationales,
  Deliveries,
  Devices,
  EntityChanges,
  ExecutionRequests,
  ExecutionTargets,
  IdempotencyKeys,
  ObjectiveAttachments,
  Objectives,
  Profiles,
  ProjectResources,
  Projects,
  ProjectStatuses,
  ProjectUserPreferences,
  RoleAssignments,
  SchemaMigrations,
  Session,
  SharedContextEntries,
  TicketEvents,
  Tickets,
  TicketSequences,
  User,
  UserTokens,
  UserTokenScopes,
  Verification,
  Workspaces,
  WorkspaceUserExecutionTargets,
  WorkspaceUsers
} from './db.js';
