// Bundle the web/REST server (`webapp/server/index.ts`) and (almost) its entire
// dependency graph into a single ESM file that runs on plain Node — no `tsx`, no
// `.ts` resolution, and no node_modules to ship except the one native addon.
// This is the file `ovld serve` runs in production and the file the desktop app
// forks inside an Electron `utilityProcess`. The dev flow keeps using `tsx
// server/index.ts` unchanged.
//
// Two packages stay external:
//   - `better-sqlite3` is a native addon that must load the build matching the
//     runtime ABI (Node for `ovld serve`, Electron for the desktop utilityProcess).
//     The cloud image omits the package from `node_modules`; Postgres boot never
//     calls the lazy loader, so the external `require` is never reached there.
//   - `@google/genai` pulls `google-auth-library`, a CommonJS package that does
//     dynamic `require()`s esbuild cannot resolve in an ESM bundle.
// The cloud build (`--cloud`) additionally skips staging the SQLite migration tree.
//
// `@overlord/database` resolves its SQL migrations relative to its own module
// location (`<dir>/../sqlite/migrations`). Once bundled, that base becomes this
// output file's directory, so we stage the migrations to `<outdir>/../sqlite/
// migrations` (mirrored into the packaged app at `app.asar/sqlite/migrations`).
import { build } from 'esbuild';
import { cpSync, mkdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const webappRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(webappRoot, '..');
const outdir = path.join(webappRoot, 'dist-server');
const cloudBuild =
  process.argv.includes('--cloud') || process.env.OVERLORD_SERVER_BUILD_TARGET === 'cloud';

const externals = ['better-sqlite3', '@google/genai'];

// CommonJS output: native `require` for the CJS dependency graph (dotenv,
// express, the google-auth chain), and esbuild shims `import.meta.url` against
// the output file's location so the bundled @overlord/database resolves its
// migrations relative to this file.
await build({
  entryPoints: [path.join(webappRoot, 'server', 'index.ts')],
  outfile: path.join(outdir, 'index.cjs'),
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  external: externals,
  sourcemap: true,
  logLevel: 'info',
  // esbuild does not shim `import.meta.url` in CJS output, so map it to a const
  // computed from the CJS `__filename`. Every module that resolves paths from
  // its own location (the server entry, db.ts, @overlord/database migrations)
  // then resolves relative to this bundle file.
  define: { 'import.meta.url': '__overlord_import_meta_url' },
  banner: {
    js: [
      '// Overlord web/REST server bundle — generated by webapp/scripts/build-server.mjs. Do not edit.',
      "const __overlord_import_meta_url = require('url').pathToFileURL(__filename).href;"
    ].join('\n')
  }
});

// Stage the migrations one directory up from the bundle so the bundled
// @overlord/database (which resolves `import.meta.url/../sqlite/migrations` and
// `../postgres/migrations`) finds them at runtime.
const postgresMigrationsDest = path.join(webappRoot, 'postgres', 'migrations');
rmSync(path.join(webappRoot, 'postgres'), { recursive: true, force: true });
mkdirSync(path.dirname(postgresMigrationsDest), { recursive: true });
cpSync(path.join(repoRoot, 'database', 'postgres', 'migrations'), postgresMigrationsDest, {
  recursive: true
});

if (cloudBuild) {
  rmSync(path.join(webappRoot, 'sqlite'), { recursive: true, force: true });
  console.log('Built webapp/dist-server/index.cjs (cloud: postgres migrations only)');
} else {
  const sqliteMigrationsDest = path.join(webappRoot, 'sqlite', 'migrations');
  rmSync(path.join(webappRoot, 'sqlite'), { recursive: true, force: true });
  mkdirSync(path.dirname(sqliteMigrationsDest), { recursive: true });
  cpSync(path.join(repoRoot, 'database', 'sqlite', 'migrations'), sqliteMigrationsDest, {
    recursive: true
  });
  console.log(
    'Built webapp/dist-server/index.cjs (+ staged sqlite/migrations and postgres/migrations)'
  );
}
