// Production CLI build: typecheck-friendly tsc emit for tests, then esbuild bundles
// `src/index.ts` (and its dependency graph, including `@overlord/core`) into a single
// self-contained `dist/index.js` for npm publish and the desktop app staging dir.
import { spawnSync } from 'node:child_process';
import { cpSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const cliRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(cliRoot, '..');
const tsc = path.join(repoRoot, 'node_modules', '.bin', 'tsc');

// Native / server-only packages the published CLI must not ship or execute.
// `yaml` is deliberately NOT here: it is a pure-JS runtime dependency of
// `src/contract.ts`, and the desktop app stages only `dist/index.js` +
// `package.json` (no node_modules), so an externalized import cannot resolve
// at runtime. It must be bundled into `dist/index.js`.
const bundleExternals = ['better-sqlite3', '@overlord/database', '@overlord/auth', 'kysely'];

function run(command, args, cwd = cliRoot) {
  const result = spawnSync(command, args, { cwd, stdio: 'inherit' });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

rmSync(path.join(cliRoot, 'dist'), { recursive: true, force: true });

run('yarn', ['workspace', '@overlord/core', 'build'], repoRoot);
run('yarn', ['workspace', '@overlord/contract', 'build'], repoRoot);

// Per-module emit for unit tests that import individual `dist/*.js` modules.
run(tsc, ['--project', 'tsconfig.build.json'], cliRoot);

await build({
  entryPoints: [path.join(cliRoot, 'src', 'index.ts')],
  outfile: path.join(cliRoot, 'dist', 'index.js'),
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  external: bundleExternals,
  sourcemap: true,
  logLevel: 'info',
  banner: {
    // `yaml` ships its Node build as CommonJS and dynamically loads Node
    // built-ins such as `process` and `buffer`. In an ESM bundle esbuild's
    // generated dynamic-require shim otherwise throws before parsing YAML.
    // Keep the dependency bundled while giving that shim a Node resolver.
    js:
      "import { createRequire } from 'node:module';\n" +
      "const require = createRequire(import.meta.url);\n" +
      '// Overlord CLI bundle — generated by cli/scripts/build.mjs. Do not edit.'
  }
});

cpSync(path.join(repoRoot, 'connectors'), path.join(cliRoot, 'dist', 'connectors'), {
  recursive: true,
  filter: source => path.basename(source) !== '.DS_Store'
});

cpSync(
  path.join(repoRoot, 'contract', 'conformance-manifest.schema.yaml'),
  path.join(cliRoot, 'dist', 'contract', 'conformance-manifest.schema.yaml')
);

console.log('Bundled cli/dist/index.js (includes @overlord/core) for npm/desktop runtime.');
